#!/usr/bin/env python3
"""Regenerate src/ge_asset_manifest.inc from a known-good game dump.

The manifest is the ground truth for the startup asset check
(src/ge_asset_check.cpp): every file listed must exist under the game data
root or the game refuses to launch and tells the user what is missing.

Only the runtime payload is listed. Deliberately EXCLUDED:
  - user/, cache/, ge.log, stderr.txt, ge.toml   (created at runtime)
  - savethumbnail.png                            (game-written; healthy boots
                                                  probe-and-miss it, see
                                                  out/session-2026-07-02-c/ge.log)
  - ArcadeInfo.xml, Bean_GameIMAGE.png           (XBLA dashboard metadata,
                                                  never opened by the game)
  - GoldenEye 007 XBLA/                          (raw extracted package copy)

Usage: tools/gen_asset_manifest.py [assets_dir] [output.inc]
Defaults: <repo>/assets -> <repo>/src/ge_asset_manifest.inc
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Top-level whitelist: everything under files/, plus the root payload files.
ROOT_FILES = {
    "default.xex",
    "music.xgs", "music.xsb", "music.xwb",
    "sfx.xgs", "sfx.xsb", "sfx.xwb",
}
ROOT_DIRS = {"files"}


# Local-only noise that must never enter the manifest: editor/test leftovers
# (a stray default.rba.bak in the reference dump once flagged every healthy
# install) and hidden files.
BLOCKED_SUFFIXES = (".bak", ".orig", ".tmp")


def collect(assets: Path) -> list[str]:
    out = []
    for p in sorted(assets.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(assets).as_posix()
        low = rel.lower()
        if low.endswith(BLOCKED_SUFFIXES) or p.name.startswith("."):
            continue
        top = rel.split("/", 1)[0]
        if low in ROOT_FILES or top.lower() in ROOT_DIRS:
            out.append(low)
    return sorted(out)


def main() -> int:
    assets = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO / "assets"
    output = Path(sys.argv[2]) if len(sys.argv) > 2 else REPO / "src" / "ge_asset_manifest.inc"
    if not (assets / "default.xex").is_file():
        print(f"error: {assets} does not look like a game dump (no default.xex)",
              file=sys.stderr)
        return 1

    paths = collect(assets)
    missing_root = ROOT_FILES - {p for p in paths if "/" not in p}
    if missing_root:
        print(f"warning: dump lacks expected root files: {sorted(missing_root)}",
              file=sys.stderr)

    with output.open("w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by tools/gen_asset_manifest.py -- do not edit by hand.\n")
        f.write("// Required game files, relative to the game data root\n")
        f.write("// (lowercase, forward slashes). Regenerate against a known-good\n")
        f.write("// dump after any change to the shipped asset set.\n")
        f.write(f"// {len(paths)} files.\n")
        f.write("inline constexpr const char* kGeRequiredAssets[] = {\n")
        for p in paths:
            escaped = p.replace("\\", "\\\\").replace('"', '\\"')
            f.write(f'    "{escaped}",\n')
        f.write("};\n")
    print(f"wrote {output} ({len(paths)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
